export const appointments = [

    {
        key:"appointment1",
        patientId: "1",
        appointmentId: "1",
        doctorId: "1",
        room:"1",
        status:"waiting",
    },
    {
        key:"appointment2",
        patientId: "3",
        appointmentId: "2",
        doctorId:"1",
        room:"2",
        status:"waiting",
    },
    {
        key:"appointment3",
        patientId: "2",
        appointmentId: "3",
        doctorId:"3",
        room:"5",
        status:"consulted",
    },
    {
        key:"appointment4",
        patientId: "143",
        appointmentId: "4",
        doctorId:"1",
        room:"12",
        status:"cancel",
    },
    {
        key:"appointment5",
        patientId: "1",
        appointmentId: "5",
        status:"waiting",
    },
    {
        key:"appointment6",
        patientId: "1",
        appointmentId: "6",
        doctorId:"4",
        room:"5",
        status:"waiting",
    },
    {
        key:"appointment7",
        patientId: "1",
        appointmentId: "7",
        doctorId: "1",
        room:"1",
        status:"waiting",
    },
    {
        key:"appointment8",
        patientId: "1",
        appointmentId: "8",
        doctorId: "1",
        room:"1",
        status:"waiting",
    },
    {
        key:"appointment9",
        patientId: "1",
        appointmentId: "9",
        doctorId: "1",
        room:"1",
        status:"waiting",
    },
    {
        key:"appointment10",
        patientId: "1",
        appointmentId: "10",
        doctorId: "1",
        room:"1",
        status:"waiting",
    },
    {
        key:"appointment11",
        patientId: "1",
        appointmentId: "11",
        doctorId: "1",
        room:"1",
        status:"consulted",
    },
    {
        key:"appointment12",
        patientId: "1",
        appointmentId: "12",
        doctorId: "1",
        room:"1",
        status:"cancelled",
    },
    {
        key:"appointment13",
        patientId: "1",
        appointmentId: "13",
        doctorId: "1",
        room:"1",
        status:"waiting",
    },
    {
        key:"appointment14",
        patientId: "1",
        appointmentId: "14",
        doctorId: "1",
        room:"1",
        status:"consulted",
    },
    {
        key:"appointment15",
        patientId: "1",
        appointmentId: "15",
        doctorId: "1",
        room:"1",
        status:"waiting",
    },
    {
        key:"appointment16",
        patientId: "1",
        appointmentId: "16",
        doctorId: "1",
        room:"1",
        status:"waiting",
    },
    {
        key:"appointment17",
        patientId: "1",
        appointmentId: "17",
        doctorId: "1",
        room:"1",
        status:"waiting",
    },
]